apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: cicd-instances
spec:
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
