apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-registry
  name: docker-registry
  namespace: cicd-instances
spec:
  replicas: 0
  selector:
    matchLabels:
      deployment: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
        deployment: docker-registry
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/server.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/server.key
        image: registry:2.7.1
        imagePullPolicy: IfNotPresent
        name: docker-registry
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/registry
          name: empty-dir
        - mountPath: /certs
          name: docker-registry-certs
      - args:
        - apt-get -y update && apt-get -y install curl && apt-get install -y docker
          && tail -f /dev/null
        command:
        - /bin/bash
        - -c
        - --
        image: ubuntu:14.04
        name: test
      volumes:
      - emptyDir: {}
        name: empty-dir
      - name: docker-registry-certs
        secret:
          secretName: docker-registry-certs
