apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: openjdk11-build-kaniko-pipeline
spec:
  workspaces:
    - name: pipeline-workspace-tmp
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: private-registry-svc.default.svc.cluster.local:5000/openjdk11-base-image
    - name: image-tag
      type: string
      description: Docker image tag
      default: v0.0.1
    - name: dockerfile
      type: string
      description: Docker image Dockerfile
      default: ./tekton/openjdk-base-image/dockerfile/Dockerfile.basic
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/intp-a/cicd-instances.git
        - name: revision
          value: "main"
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace-tmp
    - name: build-image
      runAfter:
        - clone-repository
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(params.image-tag)"
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: EXTRA_ARGS
          value:
            - "--skip-tls-verify"
      taskRef:
        kind: Task
        name: kaniko
      workspaces:
        - name: source
          workspace: pipeline-workspace-tmp
