apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-workspace-pv
  labels:
    volume-type: tekton-tmp
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/tekton-tmp
