FROM docker.io/ubuntu:18.04
MAINTAINER "gkim" <guardkim9@nate.com>

USER root

WORKDIR /tmp/setup
COPY src/ .

RUN add-apt-repository ppa:openjdk-r/ppa​ && apt-get update​ && apt install openjdk-11-jdk language-pack-ko && apt-get clean all;
RUN locale-gen ko_KR.UTF-8
ENV LANG ko_KR.UTF-8

WORKDIR /tmp

USER 1000
